import { CaptionStyle } from '../types';

export const CAPTION_PRESETS: Record<string, CaptionStyle> = {
  classic: {
    presetName: 'Classic',
    fontFamily: 'Inter',
    fontSize: 26,
    fontWeight: 'semibold',
    textColor: '#FFFFFF',
    textTransform: 'none',
    isItalic: false,
    backgroundType: 'none',
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    position: 'bottom',
    verticalPercent: 88,
    align: 'center',
    effect: 'outline',
    outlineColor: '#000000',
    wordHighlight: false,
    highlightColor: '#FBBF24',
  },
  modern: {
    presetName: 'Modern',
    fontFamily: 'Plus Jakarta Sans',
    fontSize: 28,
    fontWeight: 'bold',
    textColor: '#FFFFFF',
    textTransform: 'none',
    isItalic: false,
    backgroundType: 'rounded',
    backgroundColor: '#0F172A',
    backgroundOpacity: 0.85,
    position: 'bottom',
    verticalPercent: 86,
    align: 'center',
    effect: 'none',
    outlineColor: '#000000',
    wordHighlight: false,
    highlightColor: '#38BDF8',
  },
  social: {
    presetName: 'Social / Reels',
    fontFamily: 'Plus Jakarta Sans',
    fontSize: 34,
    fontWeight: 'extrabold',
    textColor: '#FFFFFF',
    textTransform: 'uppercase',
    isItalic: false,
    backgroundType: 'rounded',
    backgroundColor: '#000000',
    backgroundOpacity: 0.9,
    position: 'center',
    verticalPercent: 78,
    align: 'center',
    effect: 'shadow',
    outlineColor: '#000000',
    wordHighlight: true,
    highlightColor: '#FACC15', // Vibrant yellow highlight for current word
  },
  minimal: {
    presetName: 'Minimal',
    fontFamily: 'Inter',
    fontSize: 24,
    fontWeight: 'medium',
    textColor: '#F8FAFC',
    textTransform: 'none',
    isItalic: false,
    backgroundType: 'none',
    backgroundColor: '#000000',
    backgroundOpacity: 0.5,
    position: 'bottom',
    verticalPercent: 90,
    align: 'center',
    effect: 'shadow',
    outlineColor: '#000000',
    wordHighlight: false,
    highlightColor: '#60A5FA',
  },
  highlight: {
    presetName: 'Word Pop',
    fontFamily: 'Plus Jakarta Sans',
    fontSize: 32,
    fontWeight: 'bold',
    textColor: '#E2E8F0',
    textTransform: 'none',
    isItalic: false,
    backgroundType: 'box',
    backgroundColor: '#1E1B4B',
    backgroundOpacity: 0.85,
    position: 'bottom',
    verticalPercent: 84,
    align: 'center',
    effect: 'glow',
    outlineColor: '#818CF8',
    wordHighlight: true,
    highlightColor: '#38BDF8',
  },
  cinematic: {
    presetName: 'Cinematic',
    fontFamily: 'Georgia',
    fontSize: 24,
    fontWeight: 'normal',
    textColor: '#F1F5F9',
    textTransform: 'none',
    isItalic: false,
    backgroundType: 'semi-transparent',
    backgroundColor: '#090D16',
    backgroundOpacity: 0.7,
    position: 'bottom',
    verticalPercent: 92,
    align: 'center',
    effect: 'shadow',
    outlineColor: '#000000',
    wordHighlight: false,
    highlightColor: '#F59E0B',
  },
};

export const DEFAULT_STYLE: CaptionStyle = CAPTION_PRESETS.modern;
