import { CaptionItem, CaptionStyle } from '../types';

export function formatTime(seconds: number, includeMs = true, srtFormat = false): string {
  if (isNaN(seconds) || seconds < 0) seconds = 0;
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const ms = Math.floor((seconds % 1) * 1000);

  const pad = (n: number, z = 2) => String(n).padStart(z, '0');

  const msSep = srtFormat ? ',' : '.';
  const timeStr = `${pad(h)}:${pad(m)}:${pad(s)}`;
  return includeMs ? `${timeStr}${msSep}${pad(ms, 3)}` : timeStr;
}

export function formatDisplayTime(seconds: number): string {
  if (isNaN(seconds) || seconds < 0) seconds = 0;
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const pad = (n: number) => String(n).padStart(2, '0');

  if (h > 0) {
    return `${pad(h)}:${pad(m)}:${pad(s)}`;
  }
  return `${pad(m)}:${pad(s)}`;
}

export function captionsToSRT(captions: CaptionItem[]): string {
  const sorted = [...captions].sort((a, b) => a.startTime - b.endTime);
  return sorted
    .map((cap, index) => {
      const start = formatTime(cap.startTime, true, true);
      const end = formatTime(cap.endTime, true, true);
      return `${index + 1}\n${start} --> ${end}\n${cap.text}\n`;
    })
    .join('\n');
}

export function captionsToVTT(captions: CaptionItem[]): string {
  const sorted = [...captions].sort((a, b) => a.startTime - b.endTime);
  const body = sorted
    .map((cap, index) => {
      const start = formatTime(cap.startTime, true, false);
      const end = formatTime(cap.endTime, true, false);
      const speakerPrefix = cap.speaker ? `<v ${cap.speaker}>` : '';
      return `${index + 1}\n${start} --> ${end}\n${speakerPrefix}${cap.text}\n`;
    })
    .join('\n');

  return `WEBVTT - Generated by CaptionCraft AI\n\n${body}`;
}

export function captionsToTXT(captions: CaptionItem[]): string {
  const sorted = [...captions].sort((a, b) => a.startTime - b.endTime);
  return sorted
    .map((cap) => {
      const time = `[${formatDisplayTime(cap.startTime)}]`;
      const speaker = cap.speaker ? `${cap.speaker}: ` : '';
      return `${time} ${speaker}${cap.text}`;
    })
    .join('\n\n');
}

export function captionsToASS(captions: CaptionItem[], style?: CaptionStyle): string {
  const sorted = [...captions].sort((a, b) => a.startTime - b.endTime);
  const fontName = style?.fontFamily || 'Arial';
  const fontSize = style?.fontSize || 24;

  const header = `[Script Info]
Title: CaptionCraft AI Subtitles
ScriptType: v4.00+
Collisions: Normal
PlayDepth: 0
Timer: 100.0000

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,${fontName},${fontSize},&H00FFFFFF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,2,2,2,10,10,20,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n`;

  const formatAssTime = (sec: number) => {
    const h = Math.floor(sec / 3600);
    const m = Math.floor((sec % 3600) / 60);
    const s = Math.floor(sec % 60);
    const cs = Math.floor((sec % 1) * 100);
    const pad = (n: number) => String(n).padStart(2, '0');
    return `${h}:${pad(m)}:${pad(s)}.${pad(cs)}`;
  };

  const lines = sorted.map((cap) => {
    const start = formatAssTime(cap.startTime);
    const end = formatAssTime(cap.endTime);
    const text = cap.text.replace(/\n/g, '\\N');
    return `Dialogue: 0,${start},${end},Default,,0,0,0,,${text}`;
  });

  return header + lines.join('\n');
}

export function triggerDownload(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
